service: slackapp-google-oauth-test

provider:
  name: aws
  runtime: python3.7
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:ReceiveMessage"
      Resource: "*"

functions:
  auth:
    handler: auth.invoke
    events:
      - http:
          path: auth
          method: post
    environment:
      GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
      SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
  callback:
    handler: callback.invoke
    events:
      - http:
          path: callback
          method: get
    environment:
      GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}
      TASK_QUEUE_ENDPOINT: { "Ref": "TaskQueue" }
  task:
    handler: task.invoke
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - TaskQueue
              - Arn
    environment:
      TASK_QUEUE_ENDPOINT: { "Ref": "TaskQueue" }

package:
  exclude:
    - .venv/**

resources:
  Resources:
    TaskQueue:
      Type: AWS::SQS::Queue
      Properties:
        RedrivePolicy:
          deadLetterTargetArn: 
            Fn::GetAtt:
              - TaskDLQ
              - Arn
          maxReceiveCount: 1
    TaskDLQ:
      Type: AWS::SQS::Queue

plugins:
  - serverless-python-requirements
