service: slackapp-google-oauth-test

provider:
  name: aws
  runtime: python3.7
  region: ap-northeast-1
  profile: cm-hirata.kei

functions:
  auth:
    handler: auth.invoke
    events:
      - http:
          path: auth
          method: post
    environment:
      GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
      SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
  callback:
    handler: callback.invoke
    events:
      - http:
          path: callback
          method: get
    environment:
      GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}

package:
  exclude:
    - .venv/**

plugins:
  - serverless-python-requirements
